### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cinderblockgames** [thearistotle2/ban-ad#2]
- [x] Validate image (size, dimensions) in js
- [x] Add honeypot (customizable name/id) and min time (customizable seconds) to filter bots

-> DEPLOY 2

---

- [x] Default ad (in AdSpot definition) + default default ad generation
- [x] Take in request
- [x] Validate request (including honeypot + min time)
- [x] Provide response
- [x] Set up email
- [x] Email user that it's been submitted
- [x] Processing gif on send click
- [x] Catch errors during submission

-> DEPLOY 3

---

- [x] Add link field to submission page and submitter email
- [x] Email owner submission with accept/reject links
- [x] Process Reject
- [x] Email user reject with reason (if avail)
- [x] Ad-slot-specific address (allows for separate tracking per ad slot)
- [x] Process Accept (to Accepted if BAN or Paid if free)
- [x] Email user accept (with invoice unless free)
- [x] Watch for payments (RPC)
- [x] Email user that invoice has been paid and they've entered the queue
- [x] Email user when ad is live
- [x] Serve ads
- [x] Expire ads
- [x] Test File.Create against SAN in docker.  If works, update SLSAK.
- [x] Free ads expire immediately

-> DEPLOY 4

---

- [x] Watch for payments (Explorer)
- [x] Test gifs
- [x] Add ahead of me
- [x] Make view for seeing upcoming campaigns per ad slot
- [x] README for install (include note on where to add favicon if user wants a separate one, as well as how to set up gmail)
- [x] README - NewId
- [x] Push to Docker Hub
- [x] Have client update Docker Hub README

-> FINAL DEPLOY AND DELIVERY

---

- [ ] Help client set up on own site
- [ ] Two-month bug warranty -- through **September 26, 2022**
